### 熟悉tensor创建和操作张量

In [1]:
from __future__ import print_function
import tensorflow as tf

In [2]:
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
print('primes:', primes)

primes: tf.Tensor([ 2  3  5  7 11 13], shape=(6,), dtype=int32)


In [3]:
ones = tf.ones([6], dtype=tf.int32)
print('ones:', ones)

ones: tf.Tensor([1 1 1 1 1 1], shape=(6,), dtype=int32)


In [4]:
just_beyond_primes = tf.add(primes, ones)
print('just_beyond_primes:', just_beyond_primes)

just_beyond_primes: tf.Tensor([ 3  4  6  8 12 14], shape=(6,), dtype=int32)


In [5]:
twos = tf.constant([2,2,2,2,2,2],dtype=tf.int32)
primes_doubled = primes * twos
print('primes_doubled:', primes_doubled)

primes_doubled: tf.Tensor([ 4  6 10 14 22 26], shape=(6,), dtype=int32)


In [6]:
some_matrix = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
print(some_matrix)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
print(some_matrix.numpy())

[[1 2 3]
 [4 5 6]]


### tensor的形状

In [9]:
scalar = tf.zeros([])
scalar

<tf.Tensor: id=9, shape=(), dtype=float32, numpy=0.0>

In [11]:
vector = tf.zeros([3])
vector.numpy()

array([0., 0., 0.], dtype=float32)

In [12]:
matrix = tf.zeros([2, 3])

In [13]:
matrix

<tf.Tensor: id=18, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

标量、向量、矩阵 (scalar/vector/matrix)

In [14]:
scalar = tf.zeros([])
vector = tf.zeros([3]) # 3个元素向量
matrix = tf.zeros([2,3]) # 2乘3的矩阵

print('scalar has shape',scalar.get_shape(), 'and value:\n', scalar.numpy())
print('vector has shape',vector.get_shape(), 'and value:\n', vector.numpy())
print('matrix has shape',matrix.get_shape(), 'and value:\n', matrix.numpy())

scalar has shape () and value:
 0.0
vector has shape (3,) and value:
 [0. 0. 0.]
matrix has shape (2, 3) and value:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
print("primes:", primes)

one = tf.constant(1, dtype=tf.int32)
print("one:", one)

primes: tf.Tensor([ 2  3  5  7 11 13], shape=(6,), dtype=int32)
one: tf.Tensor(1, shape=(), dtype=int32)


In [16]:
just_beyond_primes = tf.add(primes, one)
print("just_beyond_primes:", just_beyond_primes)

just_beyond_primes: tf.Tensor([ 3  4  6  8 12 14], shape=(6,), dtype=int32)


In [17]:
two = tf.constant(2, dtype=tf.int32)
primes_doubled = primes * two
print('primes_doubled:', primes_doubled)

primes_doubled: tf.Tensor([ 4  6 10 14 22 26], shape=(6,), dtype=int32)


矢量运算

In [23]:
def solution(primes):
    primes_squared = tf.multiply(primes, primes)
    neg_one = tf.constant(-1, dtype=tf.int32)
    just_under_primes_squared = tf.add(primes_squared, neg_one)
    return just_under_primes_squared

def alternative_solution(primes):
    primes_squared = tf.pow(primes, 2)
    neg_one = tf.constant(1, dtype=tf.int32)
    just_under_primes_squared = tf.subtract(primes_squared,neg_one)
    return just_under_primes_squared

primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
just_under_primes_squared = solution(primes)
print("just_under_primes_squared:", just_under_primes_squared)

just_under_primes_squared: tf.Tensor([  3   8  24  48 120 168], shape=(6,), dtype=int32)


In [24]:
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
just_under_primes_squared = alternative_solution(primes)
print("just_under_primes_squared:", just_under_primes_squared)

just_under_primes_squared: tf.Tensor([  3   8  24  48 120 168], shape=(6,), dtype=int32)


In [25]:
def solution(primes):
    primes_squared = tf.multiply(primes, primes)
    neg_one = tf.constant(-1, dtype=tf.int32)
    just_under_primes_squared = primes_squared+neg_one
    return just_under_primes_squared

In [26]:
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
just_under_primes_squared = solution(primes)
print("just_under_primes_squared:", just_under_primes_squared)

just_under_primes_squared: tf.Tensor([  3   8  24  48 120 168], shape=(6,), dtype=int32)


In [27]:
def alternative_solution(primes):
    primes_squared = tf.pow(primes, 2)
    neg_one = tf.constant(1, dtype=tf.int32)
    just_under_primes_squared = primes_squared-neg_one
    return just_under_primes_squared

In [28]:
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
just_under_primes_squared = alternative_solution(primes)
print("just_under_primes_squared:", just_under_primes_squared)

just_under_primes_squared: tf.Tensor([  3   8  24  48 120 168], shape=(6,), dtype=int32)


矩阵乘法  列数=行数 才能有效相乘

In [42]:
x = tf.constant([[5, 2, 4, 3], [5, 1, 6, -2], [-1, 3, -1, -2]],
                dtype=tf.int32)
y = tf.constant([[2, 2], [3, 5], [4, 5], [1, 6]], dtype=tf.int32)

matrix_multiply_result = tf.matmul(x, y)
print(matrix_multiply_result)

tf.Tensor(
[[35 58]
 [35 33]
 [ 1 -4]], shape=(3, 2), dtype=int32)


In [45]:
# numpy的点乘
x1 = x.numpy()
y1 = y.numpy()

print(x1.dot(y1))

[[35 58]
 [35 33]
 [ 1 -4]]


张量变形 reshape

In [46]:
matrix = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]],dtype=tf.int32)

reshaped_2x8_matrix = tf.reshape(matrix, [2, 8])
reshaped_4x4_matrix = tf.reshape(matrix, [4, 4])

In [47]:
print("Original matrix (8x2):")
print(matrix.numpy())
print("Reshaped matrix (2x8):")
print(reshaped_2x8_matrix.numpy())
print("Reshaped matrix (4x4):")
print(reshaped_4x4_matrix.numpy())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped matrix (2x8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Reshaped matrix (4x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [49]:
reshaped_2x2x4_matrix = tf.reshape(matrix, [2, 2, 4])
one_dimensional_vector = tf.reshape(matrix,[16])

print("Original matrix (8x2):")
print(matrix.numpy())
print("Reshaped 3-D tensor (2x2x4):")
print(reshaped_2x2x4_matrix.numpy())
print("1-D vector:")
print(one_dimensional_vector.numpy())

Original matrix (8x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Reshaped 3-D tensor (2x2x4):
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
1-D vector:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [50]:
a = tf.constant([5, 3, 2, 7, 1, 4])
b = tf.constant([4, 6, 3])

In [56]:
reshaped_a = tf.reshape(a, [2, 3])
reshaped_b = tf.reshape(b, [3, 1])

c = tf.matmul(reshaped_a, reshaped_b)

In [57]:
print("reshaped_a (2x3):")
print(reshaped_a.numpy())
print("reshaped_b (3x1):")
print(reshaped_b.numpy())
print("reshaped_a x reshaped_b (2x1):")
print(c.numpy())

reshaped_a (2x3):
[[5 3 2]
 [7 1 4]]
reshaped_b (3x1):
[[4]
 [6]
 [3]]
reshaped_a x reshaped_b (2x1):
[[44]
 [46]]


变量 初始化 赋值

In [60]:
# Create a scalar variable with the initial value 3.
v = tf.Variable([3])

# Create a vector variable of shape [1, 4], with random initial values,
# sampled from a normal distribution with mean 1 and standard deviation 0.35.
w = tf.Variable(tf.random_normal([1, 4], mean=1.0, stddev=0.35))

print("v:", v.numpy())
print("w:", w.numpy())

AttributeError: module 'tensorflow' has no attribute 'random_normal'